#!/bin/sh
### BEGIN INIT INFO
# Provides:          mapit
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Starts and stops mapit docker
### END INIT INFO
DOCKER=$(which docker)
SCRIPT=$DOCKER run -p 8020:80 nordgedanken/mapit-germany-docker --name "mapit"
RUNAS=daemon

PIDFILE=/var/run/mapit.pid
LOGFILE=/var/log/mapit.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS
  echo "111111111" >> /var/run/$PIDNAME
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ]; then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  rm -f "$PIDFILE"
  $DOCKER stop -t 2 mapit
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
